name = "Vulkan"
uuid = "9f14b124-c50e-4008-a7d4-969b3a6cd68a"
authors = ["Cédric Belmant"]
version = "0.1.0"

[deps]
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
VulkanCore = "16167f82-ea26-5cba-b1de-ed6fd5e30a11"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
